#version: "3.9"

services:
  olist_postgres:
    image: postgres:16
    container_name: olist_postgres
    environment:
      POSTGRES_USER: olist_user
      POSTGRES_PASSWORD: olist_pass
      POSTGRES_DB: ecom_olist
    ports:
      - "5435:5432"
    volumes:
      - olist_pgdata:/var/lib/postgresql/data

volumes:
  olist_pgdata:
